<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Avaneesh-PC" failures="2" tests="2" name="SignInNegative" time="90.92" errors="0" timestamp="2020-08-11T18:33:59 IST">
  <testcase classname="com.bixbytes.qa.cbooster.testcases.SignIn_Negative_Cases" name="signin_case_invalid_unpwd" time="11.833">
    <failure type="java.lang.AssertionError" message="expected [true] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [true]
at com.bixbytes.qa.cbooster.testcases.SignIn_Negative_Cases.signin_case_invalid_unpwd(SignIn_Negative_Cases.java:65)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- signin_case_invalid_unpwd -->
  <testcase classname="com.bixbytes.qa.cbooster.testcases.SignIn_Negative_Cases" name="signin_case_invalid_pwd" time="11.372">
    <failure type="java.lang.AssertionError" message="expected [true] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [true]
at com.bixbytes.qa.cbooster.testcases.SignIn_Negative_Cases.signin_case_invalid_pwd(SignIn_Negative_Cases.java:84)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- signin_case_invalid_pwd -->
  <testcase classname="com.bixbytes.qa.cbooster.testcases.SignIn_Negative_Cases" name="signin_checktitle_action_case" time="0.0">
    <ignored/>
  </testcase> <!-- signin_checktitle_action_case -->
</testsuite> <!-- SignInNegative -->
